# optimisation
LTO_ENABLE = yes
CONSOLE_ENABLE = yes
COMMAND_ENABLE = no

# hw features
AUDIO_ENABLE = no
BACKLIGHT_ENABLE = no
RGBLIGHT_ENABLE = yes
ENCODER_ENABLE = yes
MOUSEKEY_ENABLE = yes # scroll

# fw features
KEY_OVERRIDE_ENABLE = yes
DYNAMIC_MACRO_ENABLE = yes
EXTRAKEY_ENABLE = yes
